export enum InputType {
  TEXT = 'text',
  SELECT = 'select',
  EMAIL = 'email',
  NUMBER = 'number',
  PASSWORD = 'password',
  HIDDEN = 'hidden',
  TEXTAREA = 'textarea',
  CHECKBOX = 'checkbox',
  CHECKBOX_MODAL = 'checkboxModalInput',
  LIST = 'list',
  GROUP = 'group',
  ADDRESS = 'addressInput',
  DATE = 'date',
  TEL = 'tel',
  DATE_PICKER = 'datePickerInput',
  CURRENCY = 'unit',
  UNIT = 'unit',
}
